name: Release

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Registry Login
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Container Image
      run: cd services && docker build -t $REGISTRY/$IMAGE_NAME:latest .

    - name: Tag Latest Container Images
      run: docker tag $REGISTRY/$IMAGE_NAME:latest $REGISTRY/$IMAGE_NAME:snapshot

    - name: Push Container Image
      run: docker push $REGISTRY/$IMAGE_NAME --all-tags

